Bootstrap: shub
From: singularityhub/ubuntu

%labels
   AUTHOR david.eyre@bdi.ox.ac.uk

%post
    apt-get update && apt-get -y install python3 git wget bzip2 procps
    
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /opt/miniconda.sh
    bash /opt/miniconda.sh -b -p /opt/conda
    rm /opt/miniconda.sh
    export PATH="/opt/conda/bin:$PATH"
    
    conda config --add channels bioconda
	conda config --add channels conda-forge
    conda install bwa=0.7.15 \
				  fastqc=0.11.8 \
				  spades=3.13.1 \
				  bbmap=38.22 \
				  samtools=1.9 \
				  htslib=1.9 \
				  bcftools=1.9 \
				  blast=2.9.0 \
				  numpy=1.15.4 \
				  biopython=1.72 \
				  bedtools=2.28.0 \
				  kraken2=2.0.8_beta \
				  pandas=0.24.2 \
				  mlst=2.16.1 \
				  skesa=2.30
    
    mkdir /data
    
%environment
    export PATH="/opt/conda/bin:$PATH"
    

    